version: "3"

services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment: 
      - NODE_ENV=development
      - MONGO_USER=samle
      - MONGO_PASSWORD=mypassword
      - SESSIONS_SECRET=mysecret
    command: npm run dev
  
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=samle
      - MONGO_INITDB_ROOT_PASSWORD=mypassword